//
// Info.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Info: Codable, JSONEncodable, Hashable {

    public var count: Int
    public var pages: Int
    public var next: String?
    public var perv: String?

    public init(count: Int, pages: Int, next: String?, perv: String? = nil) {
        self.count = count
        self.pages = pages
        self.next = next
        self.perv = perv
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case pages
        case next
        case perv
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(pages, forKey: .pages)
        try container.encode(next, forKey: .next)
        try container.encodeIfPresent(perv, forKey: .perv)
    }
}

